import Vue from 'vue'

Vue.prototype.$TransactionVersion = {
  TRANSFER: 3,
  REGISTER_NAMESPACE: 2,
  MOSAIC_DEFINITION: 3,
  MOSAIC_SUPPLY_CHANGE: 2,
  MODIFY_MULTISIG_ACCOUNT: 3,
  AGGREGATE_COMPLETE: 2,
  AGGREGATE_BONDED: 2,
  LOCK: 1,
  SECRET_LOCK: 1,
  SECRET_PROOF: 1,
  ADDRESS_ALIAS: 1,
  MOSAIC_ALIAS: 1,
  MODIFY_ACCOUNT_PROPERTY_ADDRESS: 1,
  MODIFY_ACCOUNT_PROPERTY_MOSAIC: 1,
  MODIFY_ACCOUNT_PROPERTY_ENTITY_TYPE: 1,
  LINK_ACCOUNT: 2
}
